### ISSUE TITLE
foreach() in index.php

### ISSUE THREAD

**Issue by spiralofhope** [tylerhall/simple-url-shortener#3]
When visiting my `nsgsb/stats/` page, just under "Top Referers" I get:

```
Warning: Invalid argument supplied for foreach() in /path/to/index.php on line 195
```

**Comment by tylerhall** [comment]
@spiralofhope Thanks for reporting that.

Looks like that warning slipped through because I haven't been running the script with PHP errors enabled lately.

It led me to a typo that was causing top referrers on the slug stats page to be empty and leading to the error you're seeing. `git pull` the latest changes and it should be fixed 👍

**Comment by spiralofhope** [comment]
The latest `git pull` resolves the issue for me.

Thank you very much.
