### ISSUE TITLE
Track fbclid parameters in database

### ISSUE THREAD

**Issue by tylerhall** [tylerhall/simple-url-shortener#6]
From an email request...

> When using a shortened link in a facebook post, facebook automatically adds a parameter used for tracking purposes. Your shortener code does not know about this and so it does not extract the slug correctly.

> The link can look something like this:

> https://domain.tld/abcde?fbclid=IqAR6jOv0ss_tv-1oUr5z_vK2Q4gdJFDCjGW6xX4mCxby92Cg8Z21Rdxff28Y

> It would be great if your code not only would be able to extract the slug when it is followed by any kind of parameters, but also (in case of any parameters) to store these in the database, I guess. This would be optional, I'd say. A functional shortener that works with links clicked on fb would be awesome first. 😄

**Comment by Mephisztoe** [comment]
Thanks for adding this as an issue. However, meanwhile I did two things:
1st of all, I cut away parameters beginning with a "?" right away within index.php, set it as $uri and added the $uri variable as global to the respective functions so that instead of the REQUEST_URI, the altered $uri variable is used without parameters.

Then I thought about what fbclid actually is and found out that there is not much information about it available unless that it is most probably something, Facebook added recently to circumvent cookie policies. So it's actually something, I don't wanna have anyway (at the moment).

So I did the following:
Within .htaccess I added the following lines:

# Strip Facebook spyware tokens
RewriteCond %{REQUEST_METHOD} =GET [NC,OR]
RewriteCond %{REQUEST_METHOD} =HEAD [NC]
RewriteCond %{QUERY_STRING} ^(.*)&?fbclid=[^&]+$ [NC]
RewriteRule ^/?(.*)$ /$1?%1 [NE,L,R=301,E=limitcache:1]
Header always set Cache-Control "max-age=604800" env=limitcache

And then went back to your original code. Since at least it is known that the fbclid is always added as the last parameter, this rewrite rule can be safely assumed to be working and thus removing the facebook click identifier.

Information for this is taken from here: https://stackoverflow.com/questions/52847475/what-is-fbclid-the-new-facebook-parameter

For me, this issue can be closed again. :D
